---
title: "Week 6 Quiz"
author: "Nan Yang and U7627868"
date: "2023/09/01"
output:  
    html_document:
        toc: true
        toc_depth: 4
        theme: cosmo
        number_sections: false
        toc_float: true
        highlight: pygments
        fig_width: 8
        fig_height: 4
---

# Bonus section

## Loading the data
```{r}
#First let us load the data.

install.packages("tidyverse")
library(tidyverse)
library(readr)
data <- read_csv("raw_data/data.csv")
View(data)
```
```{r}
#Let us have a look on the data.
library(skimr)
skim(data)

#We can see the Data contained in this file are the following:
#NumLimbsMissing: Count data of the number of limbs missing on experimental animals
#NumLimbsRegenerating: Count data of the number of limbs regenerating based on the number of limb buds
#Vitellogenic: Yes (1) or No (0) data for whether females are vitellogenic
#Gravid: Yes (1) or No (0) data for whether females are gravid
#TempC: Mean temperature in Celcius during the experimental period
#VO2_ml_per_h: Metabolic rate (ml oxygen consumed per h)
#Weight: Dry mass of experimental animal in grams
#Sex: Female (F) or Male (M)
```

## An interesting plot

```{r}
#Let us make a plot using ggplot.

library(ggplot2)

# Let us make a gemo_plot，NumLimbsMissing is the x，NumLimbsRegenerating is the y，and use Sex to color it.

ggplot(data, aes(x = NumLimbsMissing, y = NumLimbsRegenerating, color = Sex)) +
  geom_point() +
  labs(x = "Number of Limbs Missing", y = "Number of Limbs Regenerating", color = "Sex") +
  theme_minimal()

# Let us add the facets to make it better，using Sex and Gravid.
ggplot(data, aes(x = NumLimbsMissing, y = NumLimbsRegenerating)) +
  geom_point() +
  facet_grid(Sex ~ Gravid) +
  labs(x = "Number of Limbs Missing", y = "Number of Limbs Regenerating") +
  theme_minimal()

# We can also make a boxplot，to compare the distribution of Weight in different sex.

ggplot(data, aes(x = Sex, y = weight, fill = Sex)) +
  geom_boxplot() +
  labs(x = "Sex", y = "weight", fill = "Sex") +
  theme_minimal()

# We got it!
```

